config/routes.rb
Rails.application.routes.draw do
  mount SwaggerEngine::Engine, at: '/api-docs', as: 'documentation'

  root to: 'visualization#show'

  resources :users, only: [:new, :create, :show, :update]
  get '/login',  to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get 'visualization/demographics',          to: 'visualization/demographics#index'
  get 'visualization/graduation',            to: 'visualization/graduation#index'
  get 'visualization',                       to: 'visualization#show'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get '/districts',                           to: 'districts#index'
      get '/counties',                            to: 'counties#index'
      get '/student_identifiers',                 to: 'student_identifiers#index'
      get '/demographics/district-in-year',       to: 'demographics/districts#show'
      get '/demographics/statewide-in-year',      to: 'demographics/state#show'
      get '/graduation/district-in-year',         to: 'graduation/districts#show'
      get '/graduation/district-highest-rate',    to: 'graduation/districts#highest'
      get '/graduation/county-highest-rate',      to: 'graduation/counties#highest'
      get '/graduation/county-in-year',           to: 'graduation/counties#show'
      get '/graduation/statewide-in-year',        to: 'graduation/state#show'

    end
  end
end

app/controllers/visualization/demographics_controller.rb
class Visualization::DemographicsController < ApplicationController
  def index
    @districts = District.all
  end
end

app/controllers/visualization/graduation_controller.rb
class Visualization::GraduationController < ApplicationController
  def index
    @districts = District.all
  end
end

app/controllers/visualization_controller.rb
class VisualizationController < ApplicationController
end

app/views/visualization/show.html.erb
<div class="centered title">Graphs & Charts</div>
<div class="centered subtitle">To see the raw data or do your own analysis, check out the <%= link_to "API", documentation_path %> </div>
<div class="row data-links">
  <div class="col-md-4 col-sm-4 col-xs-4">
    <p><%= link_to "District Graduation", visualization_graduation_path, class: "btn btn-default" %></p>
    <p><%= link_to "District Demographics", visualization_demographics_path, class: "btn btn-default" %></p>
  </div>
  <div class="well centered col-md-8 col-sm-8 col-xs-8 data-well">
    Click buttons to the left to see district statistics compared to state averages. Additional graphs will be added shortly!
  </div>

</div>