config/routes.rb
Rails.application.routes.draw do
  mount SwaggerEngine::Engine, at: '/api-docs', as: 'documentation'

  root to: 'visualization#show'

  resources :users, only: [:new, :create, :show, :update]
  get '/login',  to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get 'visualization/demographics',          to: 'visualization/demographics#index'
  get 'visualization/graduation',            to: 'visualization/graduation#index'
  get 'visualization',                       to: 'visualization#show'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get '/districts',                           to: 'districts#index'
      get '/counties',                            to: 'counties#index'
      get '/student_identifiers',                 to: 'student_identifiers#index'
      get '/demographics/district-in-year',       to: 'demographics/districts#show'
      get '/demographics/statewide-in-year',      to: 'demographics/state#show'
      get '/graduation/district-in-year',         to: 'graduation/districts#show'
      get '/graduation/district-highest-rate',    to: 'graduation/districts#highest'
      get '/graduation/county-highest-rate',      to: 'graduation/counties#highest'
      get '/graduation/county-in-year',           to: 'graduation/counties#show'
      get '/graduation/statewide-in-year',        to: 'graduation/state#show'

    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WadoeApi</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="header">
  <%= link_to "WA Department of Education API", root_path, class: "logo" %>
  <ul class="navbar-links">
    <%= link_to "Graphs & Charts", visualization_path %>
    <%= link_to "API Documentation", documentation_path %>
    <% if current_user %>
      <%= link_to "Your API Key", user_path(current_user) %>
      <%= link_to "Log Out", logout_path %>
    <% else %>
      <%= link_to "Sign Up (Get an API Key)", new_user_path %>
      <%= link_to "Log In", login_path %>
    <% end %>
  </ul>
  <div class="collapsed-navbar">
    <div class="menu-icon">
      <div class="horizontal-line"></div>
      <div class="horizontal-line"></div>
      <div class="horizontal-line"></div>
    </div>
    <ul class="dropdown-links hidden">
      <li class="dropdown-link"><%= link_to "Graphs & Charts", visualization_path %></li>
      <li class="dropdown-link"><%= link_to "API Documentation", documentation_path %></li>
      <% if current_user %>
        <li class="dropdown-link"><%= link_to "Your API Key", user_path(current_user) %></li>
        <li class="dropdown-link"><%= link_to "Log Out", logout_path %></li>
      <% else %>
        <li class="dropdown-link"><%= link_to "Sign Up (Get an API Key)", new_user_path %></li>
        <li class="dropdown-link"><%= link_to "Log In", login_path %></li>
      <% end %>
    </ul>
  </div>
</div>
<% flash.each do |type, message| %>
  <div class="<%= type %>">
    <%= message %>
  </div>
<% end %>
<div class="container">
  <%= yield %>
</div>

</body>
</html>